// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	transaction.proto
	block.proto

It has these top-level messages:
	Transaction
	Block
	Header
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	RefBlockNum        uint32 `protobuf:"varint,1,opt,name=RefBlockNum" json:"RefBlockNum,omitempty"`
	RefBlockHashPrefix uint32 `protobuf:"varint,2,opt,name=RefBlockHashPrefix" json:"RefBlockHashPrefix,omitempty"`
	Expiration         uint64 `protobuf:"varint,3,opt,name=Expiration" json:"Expiration,omitempty"`
	Sender             uint64 `protobuf:"varint,4,opt,name=Sender" json:"Sender,omitempty"`
	Contract           uint64 `protobuf:"varint,5,opt,name=Contract" json:"Contract,omitempty"`
	Action             uint64 `protobuf:"varint,6,opt,name=Action" json:"Action,omitempty"`
	Param              []byte `protobuf:"bytes,7,opt,name=Param,proto3" json:"Param,omitempty"`
	Signature          []byte `protobuf:"bytes,8,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transaction) GetRefBlockNum() uint32 {
	if m != nil {
		return m.RefBlockNum
	}
	return 0
}

func (m *Transaction) GetRefBlockHashPrefix() uint32 {
	if m != nil {
		return m.RefBlockHashPrefix
	}
	return 0
}

func (m *Transaction) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *Transaction) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Transaction) GetContract() uint64 {
	if m != nil {
		return m.Contract
	}
	return 0
}

func (m *Transaction) GetAction() uint64 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *Transaction) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "types.Transaction")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0x6e, 0xeb, 0x3a, 0xab, 0x07, 0x07, 0x91, 0x41, 0x44, 0x82, 0xa7, 0x9e, 0xf6,
	0xe2, 0x13, 0xa8, 0x08, 0x9e, 0x64, 0x49, 0x7d, 0x81, 0xb1, 0xa6, 0x1a, 0xb4, 0x49, 0x99, 0xa6,
	0x50, 0x9f, 0x5e, 0x69, 0xaa, 0xb6, 0x07, 0x8f, 0xdf, 0xff, 0xcd, 0x3f, 0x0c, 0x03, 0x27, 0x51,
	0xd8, 0x77, 0x5c, 0x45, 0x17, 0xfc, 0xb6, 0x95, 0x10, 0x03, 0x66, 0xf1, 0xb3, 0xb5, 0xdd, 0xd5,
	0x97, 0x82, 0xcd, 0xd3, 0x2c, 0x51, 0xc3, 0xc6, 0xd8, 0xfa, 0xf6, 0x23, 0x54, 0xef, 0x8f, 0x7d,
	0x43, 0x4a, 0xab, 0xe2, 0xd8, 0x2c, 0x23, 0xdc, 0x02, 0xfe, 0xe2, 0x03, 0x77, 0x6f, 0x3b, 0xb1,
	0xb5, 0x1b, 0x68, 0x2f, 0x0d, 0xfe, 0x63, 0xf0, 0x12, 0xe0, 0x7e, 0x68, 0x9d, 0xf0, 0xb8, 0x9f,
	0xf6, 0xb5, 0x2a, 0x56, 0x66, 0x91, 0xe0, 0x19, 0xe4, 0xa5, 0xf5, 0x2f, 0x56, 0x68, 0x95, 0xdc,
	0x0f, 0xe1, 0x39, 0xac, 0xef, 0x82, 0x8f, 0xc2, 0x55, 0xa4, 0x2c, 0x99, 0x3f, 0x1e, 0x3b, 0x37,
	0xe9, 0x5e, 0xca, 0xa7, 0xce, 0x44, 0x78, 0x0a, 0xd9, 0x8e, 0x85, 0x1b, 0x3a, 0xd0, 0xaa, 0x38,
	0x32, 0x13, 0xe0, 0x05, 0x1c, 0x96, 0xee, 0xd5, 0x73, 0xec, 0xc5, 0xd2, 0x3a, 0x99, 0x39, 0x78,
	0xce, 0xd3, 0x3f, 0xae, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xed, 0xcf, 0x90, 0x24, 0x01,
	0x00, 0x00,
}
