// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bottos-project/core/common/types/transaction.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	github.com/bottos-project/core/common/types/transaction.proto
	github.com/bottos-project/core/common/types/block.proto

It has these top-level messages:
	Transaction
	MethodName
	AccountName
	ContractName
	Block
	Header
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	Version     uint32                 `protobuf:"varint,1,opt,name=version" json:"version"`
	Cursor      uint32                 `protobuf:"varint,2,opt,name=cursor" json:"cursor"`
	CursorLabel uint32                 `protobuf:"varint,3,opt,name=cursor_label,json=cursorLabel" json:"cursor_label"`
	Lifetime    uint64                 `protobuf:"varint,4,opt,name=lifetime" json:"lifetime"`
	Sender      *AccountName           `protobuf:"bytes,5,opt,name=sender" json:"sender"`
	Contract    *ContractName          `protobuf:"bytes,6,opt,name=contract" json:"contract"`
	Method      *MethodName            `protobuf:"bytes,7,opt,name=method" json:"method"`
	Param       []byte                 `protobuf:"bytes,8,opt,name=param,proto3" json:"param"`
	Signature   *Transaction_Signature `protobuf:"bytes,9,opt,name=signature" json:"signature"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *Transaction) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *Transaction) GetLifetime() uint64 {
	if m != nil {
		return m.Lifetime
	}
	return 0
}

func (m *Transaction) GetSender() *AccountName {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Transaction) GetContract() *ContractName {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *Transaction) GetMethod() *MethodName {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *Transaction) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Transaction) GetSignature() *Transaction_Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Transaction_Signature struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature"`
	SigAlg    uint32 `protobuf:"varint,2,opt,name=sig_alg,json=sigAlg" json:"sig_alg"`
}

func (m *Transaction_Signature) Reset()                    { *m = Transaction_Signature{} }
func (m *Transaction_Signature) String() string            { return proto.CompactTextString(m) }
func (*Transaction_Signature) ProtoMessage()               {}
func (*Transaction_Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Transaction_Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction_Signature) GetSigAlg() uint32 {
	if m != nil {
		return m.SigAlg
	}
	return 0
}

type MethodName struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name"`
}

func (m *MethodName) Reset()                    { *m = MethodName{} }
func (m *MethodName) String() string            { return proto.CompactTextString(m) }
func (*MethodName) ProtoMessage()               {}
func (*MethodName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MethodName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AccountName struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name"`
}

func (m *AccountName) Reset()                    { *m = AccountName{} }
func (m *AccountName) String() string            { return proto.CompactTextString(m) }
func (*AccountName) ProtoMessage()               {}
func (*AccountName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ContractName struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name"`
}

func (m *ContractName) Reset()                    { *m = ContractName{} }
func (m *ContractName) String() string            { return proto.CompactTextString(m) }
func (*ContractName) ProtoMessage()               {}
func (*ContractName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ContractName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "types.Transaction")
	proto.RegisterType((*Transaction_Signature)(nil), "types.Transaction.Signature")
	proto.RegisterType((*MethodName)(nil), "types.MethodName")
	proto.RegisterType((*AccountName)(nil), "types.AccountName")
	proto.RegisterType((*ContractName)(nil), "types.ContractName")
}

func init() {
	proto.RegisterFile("github.com/bottos-project/core/common/types/transaction.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x31, 0x6f, 0xa3, 0x30,
	0x1c, 0xc5, 0xc5, 0x25, 0x21, 0xe1, 0x4f, 0x6e, 0x38, 0xdf, 0xe9, 0xce, 0x8a, 0x32, 0x10, 0x26,
	0xee, 0x4e, 0x01, 0xa9, 0xdd, 0x2a, 0x75, 0x48, 0xba, 0xb6, 0x1d, 0x68, 0xa7, 0x2e, 0x91, 0x71,
	0x5c, 0xe2, 0x0a, 0xdb, 0xc8, 0x36, 0x95, 0xfa, 0x5d, 0xfa, 0x61, 0xab, 0x1a, 0x12, 0x18, 0xb2,
	0x74, 0xf3, 0x7b, 0xef, 0xc7, 0xc3, 0x7a, 0x32, 0x5c, 0x97, 0xdc, 0x1e, 0x9a, 0x22, 0xa5, 0x4a,
	0x64, 0x85, 0xb2, 0x56, 0x99, 0x75, 0xad, 0xd5, 0x0b, 0xa3, 0x36, 0xa3, 0x4a, 0xb3, 0x8c, 0x2a,
	0x21, 0x94, 0xcc, 0xec, 0x5b, 0xcd, 0x4c, 0x66, 0x35, 0x91, 0x86, 0x50, 0xcb, 0x95, 0x4c, 0x6b,
	0xad, 0xac, 0x42, 0x13, 0x17, 0xc4, 0xef, 0x23, 0x08, 0x1f, 0xfb, 0x10, 0x61, 0x98, 0xbe, 0x32,
	0x6d, 0xb8, 0x92, 0xd8, 0x8b, 0xbc, 0xe4, 0x7b, 0x7e, 0x94, 0xe8, 0x37, 0xf8, 0xb4, 0xd1, 0x46,
	0x69, 0xfc, 0xcd, 0x05, 0x9d, 0x42, 0x2b, 0x98, 0xb7, 0xa7, 0x5d, 0x45, 0x0a, 0x56, 0xe1, 0x91,
	0x4b, 0xc3, 0xd6, 0xbb, 0xfd, 0xb4, 0xd0, 0x02, 0x66, 0x15, 0x7f, 0x66, 0x96, 0x0b, 0x86, 0xc7,
	0x91, 0x97, 0x8c, 0xf3, 0x93, 0x46, 0xff, 0xc0, 0x37, 0x4c, 0xee, 0x99, 0xc6, 0x93, 0xc8, 0x4b,
	0xc2, 0x0b, 0x94, 0xba, 0x8b, 0xa5, 0x1b, 0x4a, 0x55, 0x23, 0xed, 0x3d, 0x11, 0x2c, 0xef, 0x08,
	0x94, 0xc1, 0x8c, 0x2a, 0x69, 0x35, 0xa1, 0x16, 0xfb, 0x8e, 0xfe, 0xd9, 0xd1, 0x37, 0x9d, 0xed,
	0xf0, 0x13, 0x84, 0xfe, 0x82, 0x2f, 0x98, 0x3d, 0xa8, 0x3d, 0x9e, 0x3a, 0xfc, 0x47, 0x87, 0xdf,
	0x39, 0xb3, 0xed, 0x6e, 0x01, 0xf4, 0x0b, 0x26, 0x35, 0xd1, 0x44, 0xe0, 0x59, 0xe4, 0x25, 0xf3,
	0xbc, 0x15, 0xe8, 0x0a, 0x02, 0xc3, 0x4b, 0x49, 0x6c, 0xa3, 0x19, 0x0e, 0x5c, 0xc7, 0xb2, 0xeb,
	0x18, 0xac, 0x96, 0x3e, 0x1c, 0x99, 0xbc, 0xc7, 0x17, 0x5b, 0x08, 0x4e, 0x3e, 0x5a, 0x0e, 0x8b,
	0x3c, 0xf7, 0x8b, 0xde, 0x40, 0x7f, 0x60, 0x6a, 0x78, 0xb9, 0x23, 0x55, 0x79, 0x1c, 0xd7, 0xf0,
	0x72, 0x53, 0x95, 0x71, 0x04, 0xd0, 0xdf, 0x15, 0x21, 0x18, 0x4b, 0x22, 0xda, 0xef, 0x83, 0xdc,
	0x9d, 0xe3, 0x15, 0x84, 0x83, 0xa9, 0xce, 0x22, 0x31, 0xcc, 0x87, 0xfb, 0x9c, 0x63, 0xb6, 0xeb,
	0xa7, 0xff, 0x5f, 0x78, 0x4f, 0x85, 0xef, 0x1e, 0xd1, 0xe5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x16, 0x1c, 0xae, 0xb6, 0x85, 0x02, 0x00, 0x00,
}
