// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/bottos-project/core/api/basic-transaction.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
