// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bottos-project/bottos/api/chain.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SendTransactionResponse struct {
	Errcode uint32                          `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string                          `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *SendTransactionResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *SendTransactionResponse) Reset()                    { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()               {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *SendTransactionResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *SendTransactionResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendTransactionResponse) GetResult() *SendTransactionResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type SendTransactionResponse_Result struct {
	Trx     *Transaction `protobuf:"bytes,1,opt,name=trx" json:"trx,omitempty"`
	TrxHash string       `protobuf:"bytes,2,opt,name=trx_hash,json=trxHash" json:"trx_hash,omitempty"`
}

func (m *SendTransactionResponse_Result) Reset()         { *m = SendTransactionResponse_Result{} }
func (m *SendTransactionResponse_Result) String() string { return proto.CompactTextString(m) }
func (*SendTransactionResponse_Result) ProtoMessage()    {}
func (*SendTransactionResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{0, 0}
}

func (m *SendTransactionResponse_Result) GetTrx() *Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

func (m *SendTransactionResponse_Result) GetTrxHash() string {
	if m != nil {
		return m.TrxHash
	}
	return ""
}

type GetTransactionRequest struct {
	TrxHash string `protobuf:"bytes,1,opt,name=trx_hash,json=trxHash" json:"trx_hash,omitempty"`
}

func (m *GetTransactionRequest) Reset()                    { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()               {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GetTransactionRequest) GetTrxHash() string {
	if m != nil {
		return m.TrxHash
	}
	return ""
}

type GetTransactionResponse struct {
	Errcode uint32       `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *Transaction `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetTransactionResponse) Reset()                    { *m = GetTransactionResponse{} }
func (m *GetTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTransactionResponse) ProtoMessage()               {}
func (*GetTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetTransactionResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetTransactionResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetTransactionResponse) GetResult() *Transaction {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetBlockRequest struct {
	BlockNum  uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum" json:"block_num,omitempty"`
	BlockHash string `protobuf:"bytes,2,opt,name=block_hash,json=blockHash" json:"block_hash,omitempty"`
}

func (m *GetBlockRequest) Reset()                    { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()               {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetBlockRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetBlockRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type GetBlockResponse struct {
	Errcode uint32                   `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string                   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *GetBlockResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetBlockResponse) Reset()                    { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()               {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GetBlockResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetBlockResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetBlockResponse) GetResult() *GetBlockResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetBlockResponse_Result struct {
	PrevBlockHash    string         `protobuf:"bytes,1,opt,name=prev_block_hash,json=prevBlockHash" json:"prev_block_hash,omitempty"`
	BlockNum         uint64         `protobuf:"varint,2,opt,name=block_num,json=blockNum" json:"block_num,omitempty"`
	BlockHash        string         `protobuf:"bytes,3,opt,name=block_hash,json=blockHash" json:"block_hash,omitempty"`
	CursorBlockLabel uint32         `protobuf:"varint,4,opt,name=cursor_block_label,json=cursorBlockLabel" json:"cursor_block_label,omitempty"`
	BlockTime        uint64         `protobuf:"varint,5,opt,name=block_time,json=blockTime" json:"block_time,omitempty"`
	TrxMerkleRoot    string         `protobuf:"bytes,6,opt,name=trx_merkle_root,json=trxMerkleRoot" json:"trx_merkle_root,omitempty"`
	Delegate         string         `protobuf:"bytes,7,opt,name=delegate" json:"delegate,omitempty"`
	DelegateSign     string         `protobuf:"bytes,8,opt,name=delegate_sign,json=delegateSign" json:"delegate_sign,omitempty"`
	Trxs             []*Transaction `protobuf:"bytes,9,rep,name=trxs" json:"trxs,omitempty"`
}

func (m *GetBlockResponse_Result) Reset()                    { *m = GetBlockResponse_Result{} }
func (m *GetBlockResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*GetBlockResponse_Result) ProtoMessage()               {}
func (*GetBlockResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4, 0} }

func (m *GetBlockResponse_Result) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *GetBlockResponse_Result) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetBlockResponse_Result) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *GetBlockResponse_Result) GetCursorBlockLabel() uint32 {
	if m != nil {
		return m.CursorBlockLabel
	}
	return 0
}

func (m *GetBlockResponse_Result) GetBlockTime() uint64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *GetBlockResponse_Result) GetTrxMerkleRoot() string {
	if m != nil {
		return m.TrxMerkleRoot
	}
	return ""
}

func (m *GetBlockResponse_Result) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *GetBlockResponse_Result) GetDelegateSign() string {
	if m != nil {
		return m.DelegateSign
	}
	return ""
}

func (m *GetBlockResponse_Result) GetTrxs() []*Transaction {
	if m != nil {
		return m.Trxs
	}
	return nil
}

type GetInfoRequest struct {
}

func (m *GetInfoRequest) Reset()                    { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()               {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type GetInfoResponse struct {
	Errcode uint32                  `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string                  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *GetInfoResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetInfoResponse) Reset()                    { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()               {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GetInfoResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetInfoResponse) GetResult() *GetInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetInfoResponse_Result struct {
	HeadBlockNum          uint64 `protobuf:"varint,1,opt,name=head_block_num,json=headBlockNum" json:"head_block_num,omitempty"`
	HeadBlockHash         string `protobuf:"bytes,2,opt,name=head_block_hash,json=headBlockHash" json:"head_block_hash,omitempty"`
	HeadBlockTime         uint64 `protobuf:"varint,3,opt,name=head_block_time,json=headBlockTime" json:"head_block_time,omitempty"`
	HeadBlockDelegate     string `protobuf:"bytes,4,opt,name=head_block_delegate,json=headBlockDelegate" json:"head_block_delegate,omitempty"`
	CursorLabel           uint32 `protobuf:"varint,5,opt,name=cursor_label,json=cursorLabel" json:"cursor_label,omitempty"`
	LastConsensusBlockNum uint64 `protobuf:"varint,6,opt,name=last_consensus_block_num,json=lastConsensusBlockNum" json:"last_consensus_block_num,omitempty"`
}

func (m *GetInfoResponse_Result) Reset()                    { *m = GetInfoResponse_Result{} }
func (m *GetInfoResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*GetInfoResponse_Result) ProtoMessage()               {}
func (*GetInfoResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6, 0} }

func (m *GetInfoResponse_Result) GetHeadBlockNum() uint64 {
	if m != nil {
		return m.HeadBlockNum
	}
	return 0
}

func (m *GetInfoResponse_Result) GetHeadBlockHash() string {
	if m != nil {
		return m.HeadBlockHash
	}
	return ""
}

func (m *GetInfoResponse_Result) GetHeadBlockTime() uint64 {
	if m != nil {
		return m.HeadBlockTime
	}
	return 0
}

func (m *GetInfoResponse_Result) GetHeadBlockDelegate() string {
	if m != nil {
		return m.HeadBlockDelegate
	}
	return ""
}

func (m *GetInfoResponse_Result) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *GetInfoResponse_Result) GetLastConsensusBlockNum() uint64 {
	if m != nil {
		return m.LastConsensusBlockNum
	}
	return 0
}

type GetAccountRequest struct {
	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
}

func (m *GetAccountRequest) Reset()                    { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()               {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *GetAccountRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

type GetAccountResponse struct {
	Errcode uint32                     `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string                     `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *GetAccountResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetAccountResponse) Reset()                    { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()               {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *GetAccountResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAccountResponse) GetResult() *GetAccountResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetAccountResponse_Result struct {
	AccountName   string `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	Pubkey        string `protobuf:"bytes,2,opt,name=pubkey" json:"pubkey,omitempty"`
	Balance       uint64 `protobuf:"varint,3,opt,name=balance" json:"balance,omitempty"`
	StakedBalance uint64 `protobuf:"varint,4,opt,name=staked_balance,json=stakedBalance" json:"staked_balance,omitempty"`
}

func (m *GetAccountResponse_Result) Reset()                    { *m = GetAccountResponse_Result{} }
func (m *GetAccountResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*GetAccountResponse_Result) ProtoMessage()               {}
func (*GetAccountResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8, 0} }

func (m *GetAccountResponse_Result) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *GetAccountResponse_Result) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *GetAccountResponse_Result) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetAccountResponse_Result) GetStakedBalance() uint64 {
	if m != nil {
		return m.StakedBalance
	}
	return 0
}

type GetKeyValueRequest struct {
	Contract string `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Object   string `protobuf:"bytes,2,opt,name=object" json:"object,omitempty"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *GetKeyValueRequest) Reset()                    { *m = GetKeyValueRequest{} }
func (m *GetKeyValueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKeyValueRequest) ProtoMessage()               {}
func (*GetKeyValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *GetKeyValueRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GetKeyValueRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *GetKeyValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetKeyValueResponse struct {
	Errcode uint32                      `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string                      `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *GetKeyValueResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetKeyValueResponse) Reset()                    { *m = GetKeyValueResponse{} }
func (m *GetKeyValueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKeyValueResponse) ProtoMessage()               {}
func (*GetKeyValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *GetKeyValueResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetKeyValueResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetKeyValueResponse) GetResult() *GetKeyValueResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetKeyValueResponse_Result struct {
	Contract string `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Object   string `protobuf:"bytes,2,opt,name=object" json:"object,omitempty"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value    string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *GetKeyValueResponse_Result) Reset()                    { *m = GetKeyValueResponse_Result{} }
func (m *GetKeyValueResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*GetKeyValueResponse_Result) ProtoMessage()               {}
func (*GetKeyValueResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10, 0} }

func (m *GetKeyValueResponse_Result) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GetKeyValueResponse_Result) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *GetKeyValueResponse_Result) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetKeyValueResponse_Result) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetAbiRequest struct {
	Contract string `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
}

func (m *GetAbiRequest) Reset()                    { *m = GetAbiRequest{} }
func (m *GetAbiRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAbiRequest) ProtoMessage()               {}
func (*GetAbiRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *GetAbiRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type GetAbiResponse struct {
	Errcode uint32 `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  string `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetAbiResponse) Reset()                    { *m = GetAbiResponse{} }
func (m *GetAbiResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAbiResponse) ProtoMessage()               {}
func (*GetAbiResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *GetAbiResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetAbiResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAbiResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetTransferCreditRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spender string `protobuf:"bytes,2,opt,name=spender" json:"spender,omitempty"`
}

func (m *GetTransferCreditRequest) Reset()                    { *m = GetTransferCreditRequest{} }
func (m *GetTransferCreditRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTransferCreditRequest) ProtoMessage()               {}
func (*GetTransferCreditRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *GetTransferCreditRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetTransferCreditRequest) GetSpender() string {
	if m != nil {
		return m.Spender
	}
	return ""
}

type GetTransferCreditResponse struct {
	Errcode uint32                            `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Msg     string                            `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result  *GetTransferCreditResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetTransferCreditResponse) Reset()                    { *m = GetTransferCreditResponse{} }
func (m *GetTransferCreditResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTransferCreditResponse) ProtoMessage()               {}
func (*GetTransferCreditResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *GetTransferCreditResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetTransferCreditResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetTransferCreditResponse) GetResult() *GetTransferCreditResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetTransferCreditResponse_Result struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spender string `protobuf:"bytes,2,opt,name=spender" json:"spender,omitempty"`
	Limit   uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetTransferCreditResponse_Result) Reset()         { *m = GetTransferCreditResponse_Result{} }
func (m *GetTransferCreditResponse_Result) String() string { return proto.CompactTextString(m) }
func (*GetTransferCreditResponse_Result) ProtoMessage()    {}
func (*GetTransferCreditResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{14, 0}
}

func (m *GetTransferCreditResponse_Result) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetTransferCreditResponse_Result) GetSpender() string {
	if m != nil {
		return m.Spender
	}
	return ""
}

func (m *GetTransferCreditResponse_Result) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*SendTransactionResponse)(nil), "api.SendTransactionResponse")
	proto.RegisterType((*SendTransactionResponse_Result)(nil), "api.SendTransactionResponse.Result")
	proto.RegisterType((*GetTransactionRequest)(nil), "api.GetTransactionRequest")
	proto.RegisterType((*GetTransactionResponse)(nil), "api.GetTransactionResponse")
	proto.RegisterType((*GetBlockRequest)(nil), "api.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "api.GetBlockResponse")
	proto.RegisterType((*GetBlockResponse_Result)(nil), "api.GetBlockResponse.Result")
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "api.GetInfoResponse")
	proto.RegisterType((*GetInfoResponse_Result)(nil), "api.GetInfoResponse.Result")
	proto.RegisterType((*GetAccountRequest)(nil), "api.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "api.GetAccountResponse")
	proto.RegisterType((*GetAccountResponse_Result)(nil), "api.GetAccountResponse.Result")
	proto.RegisterType((*GetKeyValueRequest)(nil), "api.GetKeyValueRequest")
	proto.RegisterType((*GetKeyValueResponse)(nil), "api.GetKeyValueResponse")
	proto.RegisterType((*GetKeyValueResponse_Result)(nil), "api.GetKeyValueResponse.Result")
	proto.RegisterType((*GetAbiRequest)(nil), "api.GetAbiRequest")
	proto.RegisterType((*GetAbiResponse)(nil), "api.GetAbiResponse")
	proto.RegisterType((*GetTransferCreditRequest)(nil), "api.GetTransferCreditRequest")
	proto.RegisterType((*GetTransferCreditResponse)(nil), "api.GetTransferCreditResponse")
	proto.RegisterType((*GetTransferCreditResponse_Result)(nil), "api.GetTransferCreditResponse.Result")
}

func init() { proto.RegisterFile("github.com/bottos-project/bottos/api/chain.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1014 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xd6, 0x5a, 0xb2, 0x2c, 0x8f, 0xac, 0x58, 0xa1, 0xff, 0x36, 0x72, 0x92, 0x2a, 0x1b, 0xc7,
	0x10, 0xd0, 0x56, 0x2e, 0x9c, 0xc2, 0x41, 0x51, 0x14, 0x45, 0xe5, 0x02, 0x4a, 0x91, 0x9f, 0x83,
	0x62, 0xf4, 0x90, 0x8b, 0x40, 0xad, 0x18, 0x69, 0xeb, 0xdd, 0xa5, 0xca, 0xe5, 0x06, 0xca, 0xbd,
	0xa7, 0x3e, 0x43, 0xdf, 0xa5, 0xd7, 0x02, 0xbd, 0xf6, 0x01, 0xfa, 0x26, 0x29, 0xf8, 0xb7, 0xda,
	0xa5, 0x65, 0xd7, 0x15, 0x7a, 0xe3, 0x0c, 0x67, 0x86, 0xdf, 0xcc, 0x37, 0xe4, 0x10, 0xbe, 0x98,
	0x04, 0x7c, 0x9a, 0x8e, 0xba, 0x3e, 0x8d, 0x4e, 0x46, 0x94, 0x73, 0x9a, 0x7c, 0x3e, 0x63, 0xf4,
	0x27, 0xe2, 0x73, 0x2d, 0x9e, 0xe0, 0x59, 0x70, 0xe2, 0x4f, 0x71, 0x10, 0x77, 0x67, 0x8c, 0x72,
	0x8a, 0xca, 0x78, 0x16, 0xb4, 0xce, 0x6e, 0xe5, 0xc6, 0x19, 0x8e, 0x13, 0xec, 0xf3, 0x80, 0x6a,
	0x67, 0xef, 0x4f, 0x07, 0x0e, 0xde, 0x90, 0x78, 0x7c, 0xb1, 0xd8, 0x19, 0x90, 0x64, 0x46, 0xe3,
	0x84, 0x20, 0x17, 0x36, 0x08, 0x63, 0x3e, 0x1d, 0x13, 0xd7, 0x69, 0x3b, 0x9d, 0xc6, 0xc0, 0x88,
	0xa8, 0x09, 0xe5, 0x28, 0x99, 0xb8, 0x6b, 0x6d, 0xa7, 0xb3, 0x39, 0x10, 0x4b, 0xf4, 0x35, 0x54,
	0x19, 0x49, 0xd2, 0x90, 0xbb, 0xe5, 0xb6, 0xd3, 0xa9, 0x9f, 0x3e, 0xee, 0xe2, 0x59, 0xd0, 0xbd,
	0x26, 0x72, 0x77, 0x20, 0x4d, 0x07, 0xda, 0xa5, 0xd5, 0x87, 0xaa, 0xd2, 0x20, 0x0f, 0xca, 0x9c,
	0xcd, 0xe5, 0x71, 0xf5, 0xd3, 0xa6, 0x8c, 0x91, 0xf7, 0x17, 0x9b, 0xe8, 0x1e, 0xd4, 0x38, 0x9b,
	0x0f, 0xa7, 0x38, 0x99, 0x6a, 0x04, 0x1b, 0x9c, 0xcd, 0x9f, 0xe3, 0x64, 0xea, 0x9d, 0xc2, 0x5e,
	0x9f, 0xf0, 0xc2, 0x89, 0x3f, 0xa7, 0x24, 0xe1, 0x05, 0x1f, 0xa7, 0xe8, 0x13, 0xc3, 0xbe, 0xed,
	0xb3, 0x42, 0xfe, 0x1d, 0x2b, 0xff, 0xab, 0xd8, 0xf5, 0xbe, 0xf7, 0x0a, 0xb6, 0xfb, 0x84, 0xf7,
	0x42, 0xea, 0x5f, 0x1a, 0x74, 0x87, 0xb0, 0x39, 0x12, 0xf2, 0x30, 0x4e, 0x23, 0x7d, 0x54, 0x4d,
	0x2a, 0x5e, 0xa7, 0x11, 0x7a, 0x00, 0xa0, 0x36, 0x73, 0x09, 0x2b, 0x73, 0x09, 0xff, 0xf7, 0x32,
	0x34, 0x17, 0xf1, 0x56, 0x40, 0xfe, 0xa5, 0x85, 0xfc, 0xbe, 0x44, 0x6e, 0x87, 0xb4, 0x29, 0xfb,
	0x63, 0x2d, 0xe3, 0xec, 0x18, 0xb6, 0x67, 0x8c, 0xbc, 0x1f, 0xe6, 0x50, 0xaa, 0x12, 0x37, 0x84,
	0xba, 0x67, 0x90, 0x16, 0xb3, 0x5c, 0xbb, 0x31, 0xcb, 0xb2, 0x95, 0x25, 0xfa, 0x0c, 0x90, 0x9f,
	0xb2, 0x84, 0x32, 0x7d, 0x4a, 0x88, 0x47, 0x24, 0x74, 0x2b, 0x32, 0x48, 0x53, 0xed, 0xc8, 0x83,
	0x5e, 0x0a, 0xfd, 0x22, 0x18, 0x0f, 0x22, 0xe2, 0xae, 0xb7, 0x9d, 0x4e, 0x45, 0x07, 0xbb, 0x08,
	0x22, 0x22, 0x00, 0x8b, 0x66, 0x88, 0x08, 0xbb, 0x0c, 0xc9, 0x90, 0x51, 0xca, 0xdd, 0xaa, 0x02,
	0xcc, 0xd9, 0xfc, 0x95, 0xd4, 0x0e, 0x28, 0xe5, 0xa8, 0x05, 0xb5, 0x31, 0x09, 0xc9, 0x04, 0x73,
	0xe2, 0x6e, 0x48, 0x83, 0x4c, 0x46, 0x8f, 0xa1, 0x61, 0xd6, 0xc3, 0x24, 0x98, 0xc4, 0x6e, 0x4d,
	0x1a, 0x6c, 0x19, 0xe5, 0x9b, 0x60, 0x12, 0xa3, 0x23, 0xa8, 0x70, 0x36, 0x4f, 0xdc, 0xcd, 0x76,
	0x79, 0x69, 0x4b, 0xc8, 0x5d, 0xaf, 0x09, 0x77, 0xfa, 0x84, 0xff, 0x10, 0xbf, 0xa3, 0xba, 0x1f,
	0xbc, 0x8f, 0x6b, 0xb2, 0x47, 0x94, 0x6a, 0x05, 0x4a, 0x9f, 0x5a, 0x94, 0x1e, 0x1a, 0x4a, 0xf3,
	0x11, 0x6d, 0x46, 0x7f, 0x5d, 0x30, 0x7a, 0x04, 0x77, 0xa6, 0x04, 0x8f, 0x87, 0x76, 0x53, 0x6e,
	0x09, 0x6d, 0xcf, 0x50, 0x76, 0x0c, 0xdb, 0x39, 0xab, 0x5c, 0x77, 0x36, 0x32, 0x33, 0xc9, 0x5d,
	0xd1, 0x4e, 0x52, 0x52, 0x96, 0x94, 0x2c, 0xec, 0x24, 0x2d, 0x5d, 0xd8, 0xc9, 0xd9, 0x65, 0x95,
	0xaf, 0xc8, 0x98, 0x77, 0x33, 0xdb, 0xef, 0x0d, 0x05, 0x8f, 0x60, 0x4b, 0xf7, 0x84, 0xea, 0x86,
	0x75, 0x89, 0xb1, 0xae, 0x74, 0xaa, 0x11, 0x9e, 0x81, 0x1b, 0xe2, 0x84, 0x0f, 0x7d, 0x91, 0x70,
	0x9c, 0xa4, 0x49, 0x2e, 0xa5, 0xaa, 0x34, 0xdf, 0x13, 0xfb, 0xe7, 0x66, 0xdb, 0xe4, 0xe6, 0x9d,
	0xc1, 0xdd, 0x3e, 0xe1, 0xdf, 0xf9, 0x3e, 0x4d, 0x63, 0x6e, 0xae, 0xe9, 0x23, 0xd8, 0xc2, 0x4a,
	0x33, 0x8c, 0x71, 0x44, 0x74, 0x97, 0xd7, 0xb5, 0xee, 0x35, 0x8e, 0x88, 0xf7, 0xd1, 0x01, 0x94,
	0x77, 0x5c, 0x81, 0xbc, 0x33, 0x8b, 0xbc, 0x87, 0x86, 0x3c, 0x2b, 0xa8, 0xcd, 0xdf, 0x2f, 0x4e,
	0xc6, 0xdf, 0xbf, 0x03, 0x45, 0xfb, 0x50, 0x9d, 0xa5, 0xa3, 0x4b, 0xf2, 0x41, 0x1f, 0xad, 0x25,
	0x81, 0x74, 0x84, 0x43, 0x1c, 0xfb, 0x86, 0x24, 0x23, 0xa2, 0x27, 0x70, 0x27, 0xe1, 0xf8, 0x92,
	0x8c, 0x87, 0xc6, 0xa0, 0xa2, 0x58, 0x54, 0xda, 0x9e, 0x52, 0x7a, 0x6f, 0x65, 0x01, 0x5e, 0x90,
	0x0f, 0x3f, 0xe2, 0x30, 0x25, 0xa6, 0x74, 0x2d, 0xa8, 0xf9, 0x34, 0xe6, 0x0c, 0xfb, 0x5c, 0xa3,
	0xc9, 0x64, 0x01, 0x85, 0x8e, 0xc4, 0xa4, 0x32, 0x50, 0x94, 0x24, 0x4a, 0x23, 0xf0, 0xa9, 0xb7,
	0x40, 0x2c, 0xbd, 0xbf, 0x1d, 0xd8, 0x29, 0x04, 0x5f, 0xa1, 0xbc, 0xcf, 0xac, 0xf2, 0x7e, 0x62,
	0xca, 0x6b, 0x47, 0xb5, 0xeb, 0x3b, 0xce, 0xca, 0xfb, 0xbf, 0x24, 0x83, 0x76, 0x61, 0xfd, 0xbd,
	0x38, 0x4f, 0x37, 0xb8, 0x12, 0xbc, 0x4f, 0xa1, 0x21, 0xa8, 0x1e, 0x05, 0xb7, 0xa8, 0x9c, 0x77,
	0x21, 0x5f, 0x0e, 0x69, 0xbc, 0x42, 0x25, 0xf6, 0x0b, 0x95, 0xd8, 0xcc, 0x06, 0xd4, 0x73, 0x70,
	0xcd, 0x40, 0x7c, 0x47, 0xd8, 0x39, 0x23, 0xe3, 0x20, 0xbb, 0x02, 0x08, 0x2a, 0xb9, 0x8e, 0x92,
	0x6b, 0x71, 0x66, 0x32, 0x23, 0xf1, 0x98, 0x30, 0x33, 0x8e, 0xb5, 0xe8, 0xfd, 0xe5, 0xc0, 0xbd,
	0x25, 0xa1, 0x56, 0xc0, 0xfa, 0x8d, 0xc5, 0xda, 0x13, 0xc3, 0xda, 0xf2, 0xd8, 0x36, 0x77, 0x2f,
	0x33, 0xee, 0xfe, 0x53, 0x02, 0x82, 0xa3, 0x30, 0x88, 0x02, 0xae, 0xef, 0x82, 0x12, 0x4e, 0x7f,
	0xab, 0xc0, 0xfa, 0xb9, 0xf8, 0x80, 0xa1, 0x73, 0xd8, 0xb6, 0xbe, 0x38, 0xe8, 0xca, 0x2b, 0xdf,
	0xba, 0x7f, 0xd3, 0x57, 0xc8, 0x2b, 0xa1, 0x17, 0x92, 0xc5, 0x7c, 0x8c, 0x56, 0x21, 0xbb, 0xc2,
	0x4f, 0xa6, 0x75, 0xb8, 0x74, 0x2f, 0x0b, 0xf6, 0x15, 0xd4, 0xcc, 0xe8, 0x46, 0xbb, 0xd6, 0x24,
	0x57, 0x01, 0xf6, 0x96, 0xce, 0x77, 0xaf, 0x84, 0xce, 0x60, 0x43, 0x8f, 0x08, 0xb4, 0x53, 0x1c,
	0x18, 0xca, 0x71, 0x77, 0xd9, 0x14, 0xf1, 0x4a, 0xe8, 0x5b, 0x80, 0xc5, 0xeb, 0x84, 0xf6, 0xaf,
	0x3c, 0x57, 0xca, 0xfb, 0xe0, 0x9a, 0x67, 0xcc, 0x2b, 0xa1, 0x1e, 0xd4, 0x73, 0xf7, 0x0f, 0x1d,
	0x5c, 0xbd, 0x91, 0x2a, 0x84, 0x7b, 0xdd, 0x55, 0xf5, 0x4a, 0x62, 0xe4, 0xa9, 0xab, 0x80, 0x50,
	0x76, 0x50, 0x76, 0x89, 0x5a, 0x3b, 0x05, 0x5d, 0xe6, 0x74, 0x21, 0x5f, 0xf9, 0x62, 0x0b, 0xa1,
	0x07, 0xd7, 0xb5, 0x96, 0x0a, 0xf5, 0xf0, 0xe6, 0xce, 0xf3, 0x4a, 0xbd, 0xe3, 0xb7, 0x47, 0xb7,
	0xf9, 0x8c, 0x8f, 0xaa, 0xf2, 0x07, 0xfe, 0xf4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xa3,
	0x22, 0xb2, 0xf2, 0x0b, 0x00, 0x00,
}
