// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/bottos-project/core/api/core-api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/bottos-project/core/api/core-api.proto

It has these top-level messages:
	PushResponse
	QueryTrxRequest
	QueryTrxResponse
	QueryBlockRequest
	QueryBlockResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/bottos-project/core/common/types"
import _ "github.com/bottos-project/core/common/types"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Core service

type CoreClient interface {
	PushTrx(ctx context.Context, in *types.Transaction, opts ...client.CallOption) (*PushResponse, error)
	QueryTrx(ctx context.Context, in *QueryTrxRequest, opts ...client.CallOption) (*QueryTrxResponse, error)
	QueryBlock(ctx context.Context, in *QueryBlockRequest, opts ...client.CallOption) (*QueryBlockResponse, error)
}

type coreClient struct {
	c           client.Client
	serviceName string
}

func NewCoreClient(serviceName string, c client.Client) CoreClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "api"
	}
	return &coreClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *coreClient) PushTrx(ctx context.Context, in *types.Transaction, opts ...client.CallOption) (*PushResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Core.push_trx", in)
	out := new(PushResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) QueryTrx(ctx context.Context, in *QueryTrxRequest, opts ...client.CallOption) (*QueryTrxResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Core.query_trx", in)
	out := new(QueryTrxResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) QueryBlock(ctx context.Context, in *QueryBlockRequest, opts ...client.CallOption) (*QueryBlockResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Core.query_block", in)
	out := new(QueryBlockResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Core service

type CoreHandler interface {
	PushTrx(context.Context, *types.Transaction, *PushResponse) error
	QueryTrx(context.Context, *QueryTrxRequest, *QueryTrxResponse) error
	QueryBlock(context.Context, *QueryBlockRequest, *QueryBlockResponse) error
}

func RegisterCoreHandler(s server.Server, hdlr CoreHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Core{hdlr}, opts...))
}

type Core struct {
	CoreHandler
}

func (h *Core) PushTrx(ctx context.Context, in *types.Transaction, out *PushResponse) error {
	return h.CoreHandler.PushTrx(ctx, in, out)
}

func (h *Core) QueryTrx(ctx context.Context, in *QueryTrxRequest, out *QueryTrxResponse) error {
	return h.CoreHandler.QueryTrx(ctx, in, out)
}

func (h *Core) QueryBlock(ctx context.Context, in *QueryBlockRequest, out *QueryBlockResponse) error {
	return h.CoreHandler.QueryBlock(ctx, in, out)
}
