// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bottos-project/bottos/api/bottos-api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PushTrxResponse struct {
	Errcode uint32                  `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                  `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *PushTrxResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *PushTrxResponse) Reset()                    { *m = PushTrxResponse{} }
func (m *PushTrxResponse) String() string            { return proto.CompactTextString(m) }
func (*PushTrxResponse) ProtoMessage()               {}
func (*PushTrxResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *PushTrxResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *PushTrxResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PushTrxResponse) GetResult() *PushTrxResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type PushTrxResponse_Result struct {
	Trx     *Transaction `protobuf:"bytes,1,opt,name=trx" json:"trx"`
	TrxHash string       `protobuf:"bytes,2,opt,name=trx_hash,json=trxHash" json:"trx_hash"`
}

func (m *PushTrxResponse_Result) Reset()                    { *m = PushTrxResponse_Result{} }
func (m *PushTrxResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*PushTrxResponse_Result) ProtoMessage()               {}
func (*PushTrxResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

func (m *PushTrxResponse_Result) GetTrx() *Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

func (m *PushTrxResponse_Result) GetTrxHash() string {
	if m != nil {
		return m.TrxHash
	}
	return ""
}

type QueryTrxRequest struct {
	TrxHash string `protobuf:"bytes,1,opt,name=trx_hash,json=trxHash" json:"trx_hash"`
}

func (m *QueryTrxRequest) Reset()                    { *m = QueryTrxRequest{} }
func (m *QueryTrxRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryTrxRequest) ProtoMessage()               {}
func (*QueryTrxRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *QueryTrxRequest) GetTrxHash() string {
	if m != nil {
		return m.TrxHash
	}
	return ""
}

type QueryTrxResponse struct {
	Errcode uint32       `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string       `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *Transaction `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryTrxResponse) Reset()                    { *m = QueryTrxResponse{} }
func (m *QueryTrxResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryTrxResponse) ProtoMessage()               {}
func (*QueryTrxResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *QueryTrxResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryTrxResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryTrxResponse) GetResult() *Transaction {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryBlockRequest struct {
	BlockNum  uint32 `protobuf:"varint,1,opt,name=block_num,json=blockNum" json:"block_num"`
	BlockHash string `protobuf:"bytes,2,opt,name=block_hash,json=blockHash" json:"block_hash"`
}

func (m *QueryBlockRequest) Reset()                    { *m = QueryBlockRequest{} }
func (m *QueryBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryBlockRequest) ProtoMessage()               {}
func (*QueryBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *QueryBlockRequest) GetBlockNum() uint32 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *QueryBlockRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type QueryBlockResponse struct {
	Errcode uint32                     `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                     `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryBlockResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryBlockResponse) Reset()                    { *m = QueryBlockResponse{} }
func (m *QueryBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryBlockResponse) ProtoMessage()               {}
func (*QueryBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *QueryBlockResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryBlockResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryBlockResponse) GetResult() *QueryBlockResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryBlockResponse_Result struct {
	PrevBlockHash    string         `protobuf:"bytes,1,opt,name=prev_block_hash,json=prevBlockHash" json:"prev_block_hash"`
	BlockNum         uint32         `protobuf:"varint,2,opt,name=block_num,json=blockNum" json:"block_num"`
	BlockHash        string         `protobuf:"bytes,3,opt,name=block_hash,json=blockHash" json:"block_hash"`
	CursorBlockLabel uint32         `protobuf:"varint,4,opt,name=cursor_block_label,json=cursorBlockLabel" json:"cursor_block_label"`
	BlockTime        uint64         `protobuf:"varint,5,opt,name=block_time,json=blockTime" json:"block_time"`
	TrxMerkleRoot    string         `protobuf:"bytes,6,opt,name=trx_merkle_root,json=trxMerkleRoot" json:"trx_merkle_root"`
	Delegate         string         `protobuf:"bytes,7,opt,name=delegate" json:"delegate"`
	DelegateSign     string         `protobuf:"bytes,8,opt,name=delegate_sign,json=delegateSign" json:"delegate_sign"`
	Trxs             []*Transaction `protobuf:"bytes,9,rep,name=trxs" json:"trxs"`
}

func (m *QueryBlockResponse_Result) Reset()                    { *m = QueryBlockResponse_Result{} }
func (m *QueryBlockResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*QueryBlockResponse_Result) ProtoMessage()               {}
func (*QueryBlockResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4, 0} }

func (m *QueryBlockResponse_Result) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *QueryBlockResponse_Result) GetBlockNum() uint32 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *QueryBlockResponse_Result) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *QueryBlockResponse_Result) GetCursorBlockLabel() uint32 {
	if m != nil {
		return m.CursorBlockLabel
	}
	return 0
}

func (m *QueryBlockResponse_Result) GetBlockTime() uint64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *QueryBlockResponse_Result) GetTrxMerkleRoot() string {
	if m != nil {
		return m.TrxMerkleRoot
	}
	return ""
}

func (m *QueryBlockResponse_Result) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *QueryBlockResponse_Result) GetDelegateSign() string {
	if m != nil {
		return m.DelegateSign
	}
	return ""
}

func (m *QueryBlockResponse_Result) GetTrxs() []*Transaction {
	if m != nil {
		return m.Trxs
	}
	return nil
}

type QueryChainInfoRequest struct {
}

func (m *QueryChainInfoRequest) Reset()                    { *m = QueryChainInfoRequest{} }
func (m *QueryChainInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryChainInfoRequest) ProtoMessage()               {}
func (*QueryChainInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type QueryChainInfoResponse struct {
	Errcode uint32                         `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                         `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryChainInfoResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryChainInfoResponse) Reset()                    { *m = QueryChainInfoResponse{} }
func (m *QueryChainInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryChainInfoResponse) ProtoMessage()               {}
func (*QueryChainInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *QueryChainInfoResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryChainInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryChainInfoResponse) GetResult() *QueryChainInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryChainInfoResponse_Result struct {
	HeadBlockNum          uint32 `protobuf:"varint,1,opt,name=head_block_num,json=headBlockNum" json:"head_block_num"`
	HeadBlockHash         string `protobuf:"bytes,2,opt,name=head_block_hash,json=headBlockHash" json:"head_block_hash"`
	HeadBlockTime         uint64 `protobuf:"varint,3,opt,name=head_block_time,json=headBlockTime" json:"head_block_time"`
	HeadBlockDelegate     string `protobuf:"bytes,4,opt,name=head_block_delegate,json=headBlockDelegate" json:"head_block_delegate"`
	CursorLabel           uint32 `protobuf:"varint,5,opt,name=cursor_label,json=cursorLabel" json:"cursor_label"`
	LastConsensusBlockNum uint32 `protobuf:"varint,6,opt,name=last_consensus_block_num,json=lastConsensusBlockNum" json:"last_consensus_block_num"`
}

func (m *QueryChainInfoResponse_Result) Reset()         { *m = QueryChainInfoResponse_Result{} }
func (m *QueryChainInfoResponse_Result) String() string { return proto.CompactTextString(m) }
func (*QueryChainInfoResponse_Result) ProtoMessage()    {}
func (*QueryChainInfoResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6, 0}
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockNum() uint32 {
	if m != nil {
		return m.HeadBlockNum
	}
	return 0
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockHash() string {
	if m != nil {
		return m.HeadBlockHash
	}
	return ""
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockTime() uint64 {
	if m != nil {
		return m.HeadBlockTime
	}
	return 0
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockDelegate() string {
	if m != nil {
		return m.HeadBlockDelegate
	}
	return ""
}

func (m *QueryChainInfoResponse_Result) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *QueryChainInfoResponse_Result) GetLastConsensusBlockNum() uint32 {
	if m != nil {
		return m.LastConsensusBlockNum
	}
	return 0
}

type QueryAccountRequest struct {
	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name"`
}

func (m *QueryAccountRequest) Reset()                    { *m = QueryAccountRequest{} }
func (m *QueryAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryAccountRequest) ProtoMessage()               {}
func (*QueryAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *QueryAccountRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

type QueryAccountResponse struct {
	Errcode uint32                       `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                       `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryAccountResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryAccountResponse) Reset()                    { *m = QueryAccountResponse{} }
func (m *QueryAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryAccountResponse) ProtoMessage()               {}
func (*QueryAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *QueryAccountResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryAccountResponse) GetResult() *QueryAccountResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryAccountResponse_Result struct {
	AccountName   string `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name"`
	Pubkey        string `protobuf:"bytes,2,opt,name=pubkey" json:"pubkey"`
	Balance       uint64 `protobuf:"varint,3,opt,name=balance" json:"balance"`
	StakedBalance uint64 `protobuf:"varint,4,opt,name=staked_balance,json=stakedBalance" json:"staked_balance"`
}

func (m *QueryAccountResponse_Result) Reset()                    { *m = QueryAccountResponse_Result{} }
func (m *QueryAccountResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*QueryAccountResponse_Result) ProtoMessage()               {}
func (*QueryAccountResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8, 0} }

func (m *QueryAccountResponse_Result) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *QueryAccountResponse_Result) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *QueryAccountResponse_Result) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *QueryAccountResponse_Result) GetStakedBalance() uint64 {
	if m != nil {
		return m.StakedBalance
	}
	return 0
}

type QueryObjectReq struct {
	Contract string `protobuf:"bytes,1,opt,name=contract" json:"contract"`
	Object   string `protobuf:"bytes,2,opt,name=object" json:"object"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key"`
}

func (m *QueryObjectReq) Reset()                    { *m = QueryObjectReq{} }
func (m *QueryObjectReq) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectReq) ProtoMessage()               {}
func (*QueryObjectReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *QueryObjectReq) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *QueryObjectReq) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *QueryObjectReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type QueryObjectResponse struct {
	Errcode uint32                      `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                      `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryObjectResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryObjectResponse) Reset()                    { *m = QueryObjectResponse{} }
func (m *QueryObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectResponse) ProtoMessage()               {}
func (*QueryObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *QueryObjectResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryObjectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryObjectResponse) GetResult() *QueryObjectResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryObjectResponse_Result struct {
	Contract string `protobuf:"bytes,1,opt,name=contract" json:"contract"`
	Object   string `protobuf:"bytes,2,opt,name=object" json:"object"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key"`
	Value    string `protobuf:"bytes,4,opt,name=value" json:"value"`
}

func (m *QueryObjectResponse_Result) Reset()                    { *m = QueryObjectResponse_Result{} }
func (m *QueryObjectResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectResponse_Result) ProtoMessage()               {}
func (*QueryObjectResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10, 0} }

func (m *QueryObjectResponse_Result) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *QueryObjectResponse_Result) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *QueryObjectResponse_Result) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *QueryObjectResponse_Result) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PushTrxResponse)(nil), "api.PushTrxResponse")
	proto.RegisterType((*PushTrxResponse_Result)(nil), "api.PushTrxResponse.Result")
	proto.RegisterType((*QueryTrxRequest)(nil), "api.QueryTrxRequest")
	proto.RegisterType((*QueryTrxResponse)(nil), "api.QueryTrxResponse")
	proto.RegisterType((*QueryBlockRequest)(nil), "api.QueryBlockRequest")
	proto.RegisterType((*QueryBlockResponse)(nil), "api.QueryBlockResponse")
	proto.RegisterType((*QueryBlockResponse_Result)(nil), "api.QueryBlockResponse.Result")
	proto.RegisterType((*QueryChainInfoRequest)(nil), "api.QueryChainInfoRequest")
	proto.RegisterType((*QueryChainInfoResponse)(nil), "api.QueryChainInfoResponse")
	proto.RegisterType((*QueryChainInfoResponse_Result)(nil), "api.QueryChainInfoResponse.Result")
	proto.RegisterType((*QueryAccountRequest)(nil), "api.QueryAccountRequest")
	proto.RegisterType((*QueryAccountResponse)(nil), "api.QueryAccountResponse")
	proto.RegisterType((*QueryAccountResponse_Result)(nil), "api.QueryAccountResponse.Result")
	proto.RegisterType((*QueryObjectReq)(nil), "api.QueryObjectReq")
	proto.RegisterType((*QueryObjectResponse)(nil), "api.QueryObjectResponse")
	proto.RegisterType((*QueryObjectResponse_Result)(nil), "api.QueryObjectResponse.Result")
}

func init() { proto.RegisterFile("github.com/bottos-project/bottos/api/bottos-api.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 898 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x93, 0xdb, 0x34,
	0x14, 0x4f, 0xd6, 0xd9, 0x24, 0xfb, 0x92, 0xfd, 0x53, 0xed, 0x9f, 0xba, 0xd9, 0x01, 0x52, 0xb1,
	0x74, 0x72, 0x68, 0xb3, 0xc3, 0x2e, 0x43, 0x0b, 0x07, 0x98, 0x66, 0x61, 0x80, 0x01, 0x5a, 0x08,
	0x3b, 0x1c, 0xb8, 0x78, 0x14, 0x47, 0x24, 0x66, 0x6d, 0xcb, 0x2b, 0xc9, 0x9d, 0xf4, 0x0c, 0x27,
	0x66, 0xe0, 0x0b, 0x71, 0xe4, 0xc2, 0xc7, 0xe0, 0xa3, 0x30, 0x92, 0x2c, 0xdb, 0x71, 0x76, 0x5b,
	0x26, 0xd3, 0x9b, 0xf5, 0xf4, 0xd3, 0x7b, 0xbf, 0xf7, 0x7e, 0x4f, 0x7a, 0x86, 0xf7, 0x67, 0x81,
	0x9c, 0xa7, 0x93, 0xa1, 0xcf, 0xa2, 0xd3, 0x09, 0x93, 0x92, 0x89, 0x47, 0x09, 0x67, 0xbf, 0x50,
	0x5f, 0x9e, 0xfa, 0x8c, 0xd3, 0x53, 0x92, 0x04, 0xfa, 0xe3, 0x11, 0x49, 0x82, 0x61, 0xc2, 0x99,
	0x64, 0xc8, 0x21, 0x49, 0xd0, 0xfb, 0xe0, 0x7f, 0x9c, 0x93, 0x9c, 0xc4, 0x82, 0xf8, 0x32, 0x60,
	0xb1, 0x39, 0x8a, 0xff, 0xaa, 0xc3, 0xee, 0x77, 0xa9, 0x98, 0x5f, 0xf2, 0xc5, 0x98, 0x8a, 0x84,
	0xc5, 0x82, 0x22, 0x17, 0x5a, 0x94, 0x73, 0x9f, 0x4d, 0xa9, 0x5b, 0xef, 0xd7, 0x07, 0xdb, 0x63,
	0xbb, 0x44, 0x7b, 0xe0, 0x44, 0x62, 0xe6, 0x6e, 0xf4, 0xeb, 0x83, 0xad, 0xb1, 0xfa, 0x44, 0xe7,
	0xd0, 0xe4, 0x54, 0xa4, 0xa1, 0x74, 0x9d, 0x7e, 0x7d, 0xd0, 0x39, 0x3b, 0x1e, 0x2a, 0x5a, 0x15,
	0x8f, 0xc3, 0xb1, 0x86, 0x8c, 0x33, 0x68, 0xef, 0x0b, 0x68, 0x1a, 0x0b, 0xc2, 0xe0, 0x48, 0xbe,
	0xd0, 0x61, 0x3a, 0x67, 0x7b, 0xfa, 0xec, 0x65, 0xc1, 0x71, 0xac, 0x36, 0xd1, 0x3d, 0x68, 0x4b,
	0xbe, 0xf0, 0xe6, 0x44, 0xcc, 0xb3, 0xc8, 0x2d, 0xc9, 0x17, 0x5f, 0x12, 0x31, 0xc7, 0x0f, 0x61,
	0xf7, 0xfb, 0x94, 0xf2, 0x97, 0x3a, 0xd6, 0x75, 0x4a, 0x85, 0x5c, 0x42, 0xd7, 0x97, 0xd1, 0x73,
	0xd8, 0x2b, 0xd0, 0x6b, 0xe4, 0x3a, 0xa8, 0xe4, 0xba, 0xca, 0x37, 0xdb, 0xc7, 0xcf, 0xe1, 0x8e,
	0x8e, 0x34, 0x0a, 0x99, 0x7f, 0x65, 0x99, 0x1d, 0xc3, 0xd6, 0x44, 0xad, 0xbd, 0x38, 0x8d, 0xb2,
	0x60, 0x6d, 0x6d, 0x78, 0x96, 0x46, 0xe8, 0x2d, 0x00, 0xb3, 0x59, 0x4a, 0xd3, 0xc0, 0x35, 0xf5,
	0xbf, 0x1d, 0x40, 0x65, 0x8f, 0x6b, 0xb0, 0xff, 0xb0, 0xc2, 0xfe, 0x6d, 0xcd, 0x7e, 0xd5, 0x69,
	0x55, 0xac, 0x7f, 0x36, 0x72, 0xb5, 0x1e, 0xc0, 0x6e, 0xc2, 0xe9, 0x0b, 0xaf, 0xc4, 0xd4, 0x94,
	0x78, 0x5b, 0x99, 0x47, 0x96, 0xed, 0x72, 0xa6, 0x1b, 0xaf, 0xcc, 0xd4, 0xa9, 0x64, 0x8a, 0x1e,
	0x02, 0xf2, 0x53, 0x2e, 0x18, 0xcf, 0xa2, 0x84, 0x64, 0x42, 0x43, 0xb7, 0xa1, 0x9d, 0xec, 0x99,
	0x1d, 0x1d, 0xe8, 0x1b, 0x65, 0x2f, 0x9c, 0xc9, 0x20, 0xa2, 0xee, 0x66, 0xbf, 0x3e, 0x68, 0x64,
	0xce, 0x2e, 0x83, 0x88, 0x2a, 0xc2, 0xaa, 0x19, 0x22, 0xca, 0xaf, 0x42, 0xea, 0x71, 0xc6, 0xa4,
	0xdb, 0x34, 0x84, 0x25, 0x5f, 0x7c, 0xab, 0xad, 0x63, 0xc6, 0x24, 0xea, 0x41, 0x7b, 0x4a, 0x43,
	0x3a, 0x23, 0x92, 0xba, 0x2d, 0x0d, 0xc8, 0xd7, 0xe8, 0x5d, 0xd8, 0xb6, 0xdf, 0x9e, 0x08, 0x66,
	0xb1, 0xdb, 0xd6, 0x80, 0xae, 0x35, 0xfe, 0x10, 0xcc, 0x62, 0x74, 0x02, 0x0d, 0xc9, 0x17, 0xc2,
	0xdd, 0xea, 0x3b, 0x37, 0x36, 0x86, 0xde, 0xc5, 0x77, 0xe1, 0x50, 0xd7, 0xfb, 0x62, 0x4e, 0x82,
	0xf8, 0xab, 0xf8, 0x67, 0x96, 0xb5, 0x06, 0xfe, 0xc3, 0x81, 0xa3, 0xea, 0xce, 0x1a, 0x12, 0x7f,
	0x5c, 0x91, 0x18, 0x17, 0x12, 0xaf, 0x38, 0xae, 0xca, 0xfc, 0x7b, 0x21, 0xf3, 0x09, 0xec, 0xcc,
	0x29, 0x99, 0x7a, 0xd5, 0x6e, 0xed, 0x2a, 0xeb, 0xc8, 0xea, 0xf8, 0x00, 0x76, 0x4b, 0xa8, 0x52,
	0xdb, 0x6e, 0xe7, 0x30, 0x2d, 0xe8, 0x32, 0x4e, 0xeb, 0xe4, 0x68, 0x9d, 0x0a, 0x9c, 0xd6, 0x6a,
	0x08, 0xfb, 0x25, 0x5c, 0x2e, 0x47, 0x43, 0xfb, 0xbc, 0x93, 0x63, 0x3f, 0xb3, 0xba, 0xdc, 0x87,
	0x6e, 0xd6, 0x28, 0xa6, 0x45, 0x36, 0x35, 0xc7, 0x8e, 0xb1, 0x99, 0xee, 0x78, 0x0c, 0x6e, 0x48,
	0x84, 0xf4, 0x7c, 0x95, 0x70, 0x2c, 0x52, 0x51, 0x4a, 0xa9, 0xa9, 0xe1, 0x87, 0x6a, 0xff, 0xc2,
	0x6e, 0xdb, 0xdc, 0xf0, 0x13, 0xd8, 0xd7, 0x55, 0x7b, 0xea, 0xfb, 0x2c, 0x8d, 0xa5, 0xbd, 0xc1,
	0xf7, 0xa1, 0x4b, 0x8c, 0xc5, 0x8b, 0x49, 0x44, 0xb3, 0xe6, 0xef, 0x64, 0xb6, 0x67, 0x24, 0xa2,
	0xf8, 0xd7, 0x0d, 0x38, 0x58, 0x3e, 0xba, 0x86, 0x8e, 0x4f, 0x2a, 0x3a, 0xf6, 0x0b, 0x1d, 0x2b,
	0x6e, 0xab, 0x2a, 0xfe, 0x56, 0xcf, 0x55, 0x7c, 0x3d, 0x59, 0x74, 0x04, 0xcd, 0x24, 0x9d, 0x5c,
	0xd1, 0x97, 0x59, 0xf0, 0x6c, 0xa5, 0xb8, 0x4e, 0x48, 0x48, 0x62, 0xdf, 0x4a, 0x65, 0x97, 0xe8,
	0x3d, 0xd8, 0x11, 0x92, 0x5c, 0xd1, 0xa9, 0x67, 0x01, 0x0d, 0xa3, 0xa5, 0xb1, 0x8e, 0x8c, 0x11,
	0xff, 0x08, 0x3b, 0x9a, 0xed, 0xf3, 0x89, 0x9a, 0x3f, 0x63, 0x7a, 0xad, 0x6e, 0x98, 0xcf, 0x62,
	0xc9, 0x89, 0x2f, 0x33, 0x26, 0xf9, 0x5a, 0xd1, 0x60, 0x1a, 0x68, 0x69, 0x98, 0x95, 0x2a, 0x8c,
	0xe2, 0x66, 0x9e, 0x08, 0xf5, 0x89, 0xff, 0xad, 0x67, 0xc2, 0x58, 0xc7, 0x6b, 0x14, 0xf7, 0x71,
	0xa5, 0xb8, 0xef, 0x14, 0xc5, 0x5d, 0xf6, 0x5a, 0xad, 0xed, 0x34, 0x2f, 0xed, 0x1b, 0x49, 0x06,
	0x1d, 0xc0, 0xe6, 0x0b, 0x12, 0xa6, 0xb6, 0xc5, 0xcd, 0xe2, 0xec, 0x4f, 0x07, 0x5a, 0x17, 0x8c,
	0xd3, 0xa7, 0x49, 0x80, 0xce, 0xa1, 0x95, 0x4d, 0x52, 0xb4, 0xf2, 0xa4, 0xf4, 0x0e, 0x6e, 0x9a,
	0xb4, 0xb8, 0x86, 0x3e, 0x82, 0xb6, 0x9d, 0x72, 0xe8, 0xa0, 0xc8, 0xad, 0x18, 0x91, 0xbd, 0xc3,
	0x8a, 0x35, 0x3f, 0xfa, 0x29, 0x40, 0x31, 0x0f, 0xd0, 0xd1, 0xca, 0x80, 0x30, 0xc7, 0xef, 0xde,
	0x32, 0x38, 0x70, 0x0d, 0x7d, 0x9d, 0xe9, 0x9e, 0xbf, 0x36, 0xa8, 0x77, 0xe3, 0x13, 0x64, 0x1c,
	0x1d, 0xbf, 0xe2, 0x79, 0xc2, 0x35, 0xf4, 0x39, 0x74, 0xcb, 0x2d, 0x8f, 0xdc, 0x1b, 0x6e, 0x81,
	0x71, 0x74, 0xef, 0xd6, 0xfb, 0x81, 0x6b, 0xe8, 0x13, 0xe8, 0x94, 0xc4, 0x45, 0xfb, 0xab, 0x72,
	0x5f, 0xf7, 0xdc, 0xdb, 0x7a, 0x00, 0xd7, 0x46, 0x27, 0x3f, 0xe1, 0xd7, 0xff, 0x59, 0x4d, 0x9a,
	0xfa, 0x77, 0xea, 0xfc, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xb8, 0xc1, 0x17, 0xbe, 0x09,
	0x00, 0x00,
}
