// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bottos-project/core/api/core-api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/bottos-project/core/api/core-api.proto

It has these top-level messages:
	PushTrxResponse
	QueryTrxRequest
	QueryTrxResponse
	QueryBlockRequest
	QueryBlockResponse
	QueryChainInfoRequest
	QueryChainInfoResponse
	QueryAccountRequest
	QueryAccountResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/bottos-project/core/common/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushTrxResponse struct {
	Errcode uint32                  `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                  `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *PushTrxResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *PushTrxResponse) Reset()                    { *m = PushTrxResponse{} }
func (m *PushTrxResponse) String() string            { return proto.CompactTextString(m) }
func (*PushTrxResponse) ProtoMessage()               {}
func (*PushTrxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushTrxResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *PushTrxResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PushTrxResponse) GetResult() *PushTrxResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type PushTrxResponse_Result struct {
	Trx     *types.Transaction `protobuf:"bytes,1,opt,name=trx" json:"trx"`
	TrxHash []byte             `protobuf:"bytes,2,opt,name=trx_hash,json=trxHash,proto3" json:"trx_hash"`
}

func (m *PushTrxResponse_Result) Reset()                    { *m = PushTrxResponse_Result{} }
func (m *PushTrxResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*PushTrxResponse_Result) ProtoMessage()               {}
func (*PushTrxResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *PushTrxResponse_Result) GetTrx() *types.Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

func (m *PushTrxResponse_Result) GetTrxHash() []byte {
	if m != nil {
		return m.TrxHash
	}
	return nil
}

type QueryTrxRequest struct {
	TrxHash string `protobuf:"bytes,1,opt,name=trx_hash,json=trxHash" json:"trx_hash"`
}

func (m *QueryTrxRequest) Reset()                    { *m = QueryTrxRequest{} }
func (m *QueryTrxRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryTrxRequest) ProtoMessage()               {}
func (*QueryTrxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryTrxRequest) GetTrxHash() string {
	if m != nil {
		return m.TrxHash
	}
	return ""
}

type QueryTrxResponse struct {
	Errcode uint32             `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string             `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *types.Transaction `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryTrxResponse) Reset()                    { *m = QueryTrxResponse{} }
func (m *QueryTrxResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryTrxResponse) ProtoMessage()               {}
func (*QueryTrxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryTrxResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryTrxResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryTrxResponse) GetResult() *types.Transaction {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryBlockRequest struct {
	BlockHash   string `protobuf:"bytes,1,opt,name=block_hash,json=blockHash" json:"block_hash"`
	BlockNumber uint32 `protobuf:"varint,2,opt,name=block_number,json=blockNumber" json:"block_number"`
}

func (m *QueryBlockRequest) Reset()                    { *m = QueryBlockRequest{} }
func (m *QueryBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryBlockRequest) ProtoMessage()               {}
func (*QueryBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryBlockRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *QueryBlockRequest) GetBlockNumber() uint32 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type QueryBlockResponse struct {
	Errcode uint32                     `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                     `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryBlockResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryBlockResponse) Reset()                    { *m = QueryBlockResponse{} }
func (m *QueryBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryBlockResponse) ProtoMessage()               {}
func (*QueryBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryBlockResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryBlockResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryBlockResponse) GetResult() *QueryBlockResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryBlockResponse_Result struct {
	BlockHash   string `protobuf:"bytes,1,opt,name=block_hash,json=blockHash" json:"block_hash"`
	BlockNumber uint32 `protobuf:"varint,2,opt,name=block_number,json=blockNumber" json:"block_number"`
	BlockLabel  uint32 `protobuf:"varint,3,opt,name=block_label,json=blockLabel" json:"block_label"`
}

func (m *QueryBlockResponse_Result) Reset()                    { *m = QueryBlockResponse_Result{} }
func (m *QueryBlockResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*QueryBlockResponse_Result) ProtoMessage()               {}
func (*QueryBlockResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *QueryBlockResponse_Result) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *QueryBlockResponse_Result) GetBlockNumber() uint32 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *QueryBlockResponse_Result) GetBlockLabel() uint32 {
	if m != nil {
		return m.BlockLabel
	}
	return 0
}

type QueryChainInfoRequest struct {
}

func (m *QueryChainInfoRequest) Reset()                    { *m = QueryChainInfoRequest{} }
func (m *QueryChainInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryChainInfoRequest) ProtoMessage()               {}
func (*QueryChainInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type QueryChainInfoResponse struct {
	Errcode uint32                         `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                         `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryChainInfoResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryChainInfoResponse) Reset()                    { *m = QueryChainInfoResponse{} }
func (m *QueryChainInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryChainInfoResponse) ProtoMessage()               {}
func (*QueryChainInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QueryChainInfoResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryChainInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryChainInfoResponse) GetResult() *QueryChainInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryChainInfoResponse_Result struct {
	HeadBlockNum          uint32 `protobuf:"varint,1,opt,name=head_block_num,json=headBlockNum" json:"head_block_num"`
	LastConfirmedBlockNum uint32 `protobuf:"varint,2,opt,name=last_confirmed_block_num,json=lastConfirmedBlockNum" json:"last_confirmed_block_num"`
	HeadBlockHash         []byte `protobuf:"bytes,3,opt,name=head_block_hash,json=headBlockHash,proto3" json:"head_block_hash"`
	HeadBlockTime         uint64 `protobuf:"varint,4,opt,name=head_block_time,json=headBlockTime" json:"head_block_time"`
	HeadLockDelegate      string `protobuf:"bytes,5,opt,name=head_lock_delegate,json=headLockDelegate" json:"head_lock_delegate"`
}

func (m *QueryChainInfoResponse_Result) Reset()         { *m = QueryChainInfoResponse_Result{} }
func (m *QueryChainInfoResponse_Result) String() string { return proto.CompactTextString(m) }
func (*QueryChainInfoResponse_Result) ProtoMessage()    {}
func (*QueryChainInfoResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockNum() uint32 {
	if m != nil {
		return m.HeadBlockNum
	}
	return 0
}

func (m *QueryChainInfoResponse_Result) GetLastConfirmedBlockNum() uint32 {
	if m != nil {
		return m.LastConfirmedBlockNum
	}
	return 0
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockHash() []byte {
	if m != nil {
		return m.HeadBlockHash
	}
	return nil
}

func (m *QueryChainInfoResponse_Result) GetHeadBlockTime() uint64 {
	if m != nil {
		return m.HeadBlockTime
	}
	return 0
}

func (m *QueryChainInfoResponse_Result) GetHeadLockDelegate() string {
	if m != nil {
		return m.HeadLockDelegate
	}
	return ""
}

type QueryAccountRequest struct {
	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name"`
}

func (m *QueryAccountRequest) Reset()                    { *m = QueryAccountRequest{} }
func (m *QueryAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryAccountRequest) ProtoMessage()               {}
func (*QueryAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryAccountRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

type QueryAccountResponse struct {
	Errcode uint32                       `protobuf:"varint,1,opt,name=errcode" json:"errcode"`
	Msg     string                       `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Result  *QueryAccountResponse_Result `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *QueryAccountResponse) Reset()                    { *m = QueryAccountResponse{} }
func (m *QueryAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryAccountResponse) ProtoMessage()               {}
func (*QueryAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *QueryAccountResponse) GetErrcode() uint32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QueryAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryAccountResponse) GetResult() *QueryAccountResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryAccountResponse_Result struct {
	AccountName   string `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name"`
	Balance       uint64 `protobuf:"varint,2,opt,name=balance" json:"balance"`
	StakedBalance uint64 `protobuf:"varint,3,opt,name=staked_balance,json=stakedBalance" json:"staked_balance"`
}

func (m *QueryAccountResponse_Result) Reset()                    { *m = QueryAccountResponse_Result{} }
func (m *QueryAccountResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*QueryAccountResponse_Result) ProtoMessage()               {}
func (*QueryAccountResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *QueryAccountResponse_Result) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *QueryAccountResponse_Result) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *QueryAccountResponse_Result) GetStakedBalance() uint64 {
	if m != nil {
		return m.StakedBalance
	}
	return 0
}

func init() {
	proto.RegisterType((*PushTrxResponse)(nil), "api.PushTrxResponse")
	proto.RegisterType((*PushTrxResponse_Result)(nil), "api.PushTrxResponse.Result")
	proto.RegisterType((*QueryTrxRequest)(nil), "api.QueryTrxRequest")
	proto.RegisterType((*QueryTrxResponse)(nil), "api.QueryTrxResponse")
	proto.RegisterType((*QueryBlockRequest)(nil), "api.QueryBlockRequest")
	proto.RegisterType((*QueryBlockResponse)(nil), "api.QueryBlockResponse")
	proto.RegisterType((*QueryBlockResponse_Result)(nil), "api.QueryBlockResponse.Result")
	proto.RegisterType((*QueryChainInfoRequest)(nil), "api.QueryChainInfoRequest")
	proto.RegisterType((*QueryChainInfoResponse)(nil), "api.QueryChainInfoResponse")
	proto.RegisterType((*QueryChainInfoResponse_Result)(nil), "api.QueryChainInfoResponse.Result")
	proto.RegisterType((*QueryAccountRequest)(nil), "api.QueryAccountRequest")
	proto.RegisterType((*QueryAccountResponse)(nil), "api.QueryAccountResponse")
	proto.RegisterType((*QueryAccountResponse_Result)(nil), "api.QueryAccountResponse.Result")
}

func init() { proto.RegisterFile("github.com/bottos-project/core/api/core-api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xef, 0x4e, 0xdb, 0x3e,
	0x14, 0x6d, 0x28, 0x3f, 0x0a, 0xb7, 0x2d, 0xf0, 0xf3, 0xf8, 0x13, 0x8a, 0xb6, 0x15, 0x8b, 0x4d,
	0xd5, 0x04, 0xad, 0x06, 0xda, 0xc6, 0x26, 0x4d, 0x13, 0x65, 0x93, 0x86, 0x86, 0xd0, 0x16, 0xb1,
	0x2f, 0xfb, 0x52, 0xb9, 0xc1, 0x90, 0xd0, 0x24, 0xce, 0x6c, 0x47, 0x2a, 0x0f, 0xb7, 0x77, 0xd8,
	0x4b, 0x20, 0x4d, 0x7b, 0x8a, 0x29, 0x76, 0x9a, 0xa4, 0xa1, 0x0c, 0xa9, 0xfb, 0x16, 0x1f, 0x1f,
	0xdf, 0x7b, 0xee, 0x3d, 0xbe, 0x0e, 0x3c, 0xbf, 0x74, 0xa5, 0x13, 0xf5, 0xdb, 0x36, 0xf3, 0x3b,
	0x7d, 0x26, 0x25, 0x13, 0xbb, 0x21, 0x67, 0x57, 0xd4, 0x96, 0x1d, 0x9b, 0x71, 0xda, 0x21, 0xa1,
	0xab, 0x3e, 0x76, 0x49, 0xe8, 0xb6, 0x43, 0xce, 0x24, 0x43, 0x65, 0x12, 0xba, 0x8d, 0xb7, 0xf7,
	0x9c, 0xb3, 0x99, 0xef, 0xb3, 0xa0, 0x23, 0xaf, 0x43, 0x2a, 0x3a, 0x92, 0x93, 0x40, 0x10, 0x5b,
	0xba, 0x2c, 0xd0, 0x31, 0xf0, 0x0f, 0x03, 0x96, 0x3e, 0x47, 0xc2, 0x39, 0xe3, 0x43, 0x8b, 0x8a,
	0x90, 0x05, 0x82, 0x22, 0x13, 0x2a, 0x94, 0x73, 0x9b, 0x9d, 0x53, 0xd3, 0x68, 0x1a, 0xad, 0xba,
	0x35, 0x5a, 0xa2, 0x65, 0x28, 0xfb, 0xe2, 0xd2, 0x9c, 0x69, 0x1a, 0xad, 0x05, 0x2b, 0xfe, 0x44,
	0xfb, 0x30, 0xc7, 0xa9, 0x88, 0x3c, 0x69, 0x96, 0x9b, 0x46, 0xab, 0xba, 0xb7, 0xd9, 0x8e, 0xf5,
	0x15, 0x22, 0xb6, 0x2d, 0x45, 0xb1, 0x12, 0x6a, 0xe3, 0x18, 0xe6, 0x34, 0x82, 0xb6, 0xa1, 0x2c,
	0xf9, 0x50, 0xa5, 0xa9, 0xee, 0xa1, 0xb6, 0x52, 0xd9, 0x3e, 0xcb, 0x54, 0x5a, 0xf1, 0x36, 0xda,
	0x80, 0x79, 0xc9, 0x87, 0x3d, 0x87, 0x08, 0x47, 0xe5, 0xae, 0x59, 0x15, 0xc9, 0x87, 0x1f, 0x89,
	0x70, 0xf0, 0x0e, 0x2c, 0x7d, 0x89, 0x28, 0xbf, 0x56, 0xd9, 0xbe, 0x47, 0x54, 0xc8, 0x31, 0xb6,
	0xa1, 0x94, 0xa6, 0xec, 0x2b, 0x58, 0xce, 0xd8, 0x53, 0x54, 0xfb, 0xac, 0x50, 0xed, 0x24, 0xc5,
	0x09, 0x03, 0x7f, 0x85, 0xff, 0x55, 0xae, 0xae, 0xc7, 0xec, 0xc1, 0x48, 0xdb, 0x43, 0x80, 0x7e,
	0xbc, 0xce, 0xab, 0x5b, 0x50, 0x48, 0xac, 0x0f, 0x6d, 0x41, 0x4d, 0x6f, 0x07, 0x91, 0xdf, 0xa7,
	0x5c, 0xa5, 0xae, 0x5b, 0x55, 0x85, 0x9d, 0x2a, 0x08, 0xdf, 0x18, 0x80, 0xf2, 0x71, 0xa7, 0xa8,
	0xe2, 0x65, 0xa1, 0x8a, 0x47, 0xca, 0xb3, 0xdb, 0x41, 0x8b, 0xb6, 0x0d, 0x52, 0xdb, 0xfe, 0xb9,
	0x0c, 0xf4, 0x18, 0xf4, 0xb2, 0xe7, 0x91, 0x3e, 0xf5, 0x94, 0x90, 0xba, 0xa5, 0x83, 0x9e, 0xc4,
	0x08, 0x5e, 0x87, 0x55, 0xa5, 0xe8, 0xc8, 0x21, 0x6e, 0x70, 0x1c, 0x5c, 0xb0, 0xa4, 0x85, 0xf8,
	0xd7, 0x0c, 0xac, 0x15, 0x77, 0xa6, 0x68, 0xc2, 0x9b, 0x42, 0x13, 0x70, 0xd6, 0x84, 0x5b, 0x81,
	0x8b, 0x8d, 0xb8, 0x31, 0x72, 0x17, 0x78, 0xd1, 0xa1, 0xe4, 0xbc, 0x97, 0xd6, 0x9b, 0x64, 0xae,
	0xc5, 0x68, 0x37, 0x29, 0x18, 0xbd, 0x02, 0xd3, 0x23, 0x42, 0xf6, 0x6c, 0x16, 0x5c, 0xb8, 0xdc,
	0xa7, 0x79, 0xbe, 0x6e, 0xce, 0x6a, 0xbc, 0x7f, 0x34, 0xda, 0x4e, 0x0f, 0x3e, 0x85, 0xa5, 0x5c,
	0x78, 0xd5, 0xed, 0xb2, 0x1a, 0x80, 0x7a, 0x1a, 0x5f, 0x75, 0x7c, 0x9c, 0x27, 0x5d, 0x9f, 0x9a,
	0xb3, 0x4d, 0xa3, 0x35, 0x9b, 0xe3, 0x9d, 0xb9, 0x3e, 0x45, 0x3b, 0x80, 0x14, 0x4f, 0xd1, 0xce,
	0xa9, 0x47, 0x2f, 0x89, 0xa4, 0xe6, 0x7f, 0xaa, 0x2d, 0xcb, 0xf1, 0xce, 0x09, 0xb3, 0x07, 0xef,
	0x13, 0x1c, 0x1f, 0xc0, 0x03, 0xd5, 0x90, 0x43, 0xdb, 0x66, 0x51, 0x20, 0x47, 0x97, 0x78, 0x0b,
	0x6a, 0x44, 0x23, 0xbd, 0x80, 0xf8, 0x34, 0xf1, 0xbf, 0x9a, 0x60, 0xa7, 0xc4, 0xa7, 0xf8, 0xb7,
	0x01, 0x2b, 0xe3, 0x47, 0xa7, 0xb0, 0xe8, 0xa0, 0x60, 0x51, 0x33, 0xb3, 0xa8, 0x10, 0xb6, 0x68,
	0x90, 0x97, 0xfa, 0x73, 0xbf, 0xd6, 0x58, 0x52, 0x9f, 0x78, 0x24, 0xb0, 0xa9, 0x4a, 0x3e, 0x6b,
	0x8d, 0x96, 0xe8, 0x09, 0x2c, 0x0a, 0x49, 0x06, 0xb1, 0x5d, 0x09, 0xa1, 0xac, 0x9b, 0xaa, 0xd1,
	0xae, 0x06, 0xf7, 0x7e, 0xce, 0x40, 0xe5, 0x88, 0x71, 0x7a, 0x18, 0xba, 0xe8, 0x05, 0x54, 0x92,
	0xc7, 0x0f, 0x4d, 0x78, 0x1c, 0x1a, 0x2b, 0x93, 0x9e, 0x47, 0x5c, 0x42, 0xaf, 0x61, 0x7e, 0xf4,
	0x30, 0xa1, 0x95, 0xac, 0xcc, 0xec, 0x55, 0x6b, 0xac, 0x16, 0xd0, 0xf4, 0xe8, 0x3b, 0x80, 0x6c,
	0x74, 0xd1, 0xda, 0xad, 0x59, 0xd6, 0xc7, 0xd7, 0xef, 0x98, 0x71, 0x5c, 0x42, 0x9f, 0x60, 0x71,
	0xfc, 0xda, 0xa3, 0xc6, 0xc4, 0x59, 0xd0, 0x81, 0x36, 0xff, 0x32, 0x27, 0xb8, 0x84, 0x3e, 0x40,
	0x2d, 0x6f, 0x10, 0x32, 0x27, 0x78, 0xa6, 0x03, 0x6d, 0xdc, 0xe9, 0x26, 0x2e, 0x75, 0xb7, 0xbf,
	0xe1, 0xfb, 0xff, 0x87, 0xfd, 0x39, 0xf5, 0x0f, 0xdb, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9b,
	0xfe, 0x49, 0x34, 0x3c, 0x07, 0x00, 0x00,
}
