// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/bottos-project/bottos/api/transaction.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/bottos-project/bottos/api/transaction.proto
	github.com/bottos-project/bottos/api/basic-transaction.proto
	github.com/bottos-project/bottos/api/chain.proto

It has these top-level messages:
	Transaction
	BasicTransaction
	SendTransactionResponse
	GetTransactionRequest
	GetTransactionResponse
	GetBlockRequest
	GetBlockResponse
	GetInfoRequest
	GetInfoResponse
	GetAccountRequest
	GetAccountResponse
	GetKeyValueRequest
	GetKeyValueResponse
	GetAbiRequest
	GetAbiResponse
	GetTransferCreditRequest
	GetTransferCreditResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
